### ISSUE TITLE
ios screen is not rotating when locking orientation

### ISSUE THREAD

**Issue by melody1798** [gbenvenuti/cordova-plugin-screen-orientation#117]
I used default branch with IONIC.
The screen is not rotating when I lock the orientation to landscape.

Looking for your advice.
Thanks

**Comment by tony--** [comment]
@melody1798 thanks for the report.
This repository is no longer being maintained (see README for more information).
I think this issue is already logged in the Apache Cordova JIRA for the "Plugin Screen Orientation" component, take a look at [CB-11359](https://issues.apache.org/jira/browse/CB-11359).
