### ISSUE TITLE
Get the current state

### ISSUE THREAD

**Issue by TorokDaniel** [gbenvenuti/cordova-plugin-screen-orientation#66]
A new API method would be nice, where we can see the plugin's current state (unlocked, or locked to a specific orientation). There is a private property for this in the .js file, but it is not published on the screen object.

Example - why would anyone need this:

Someone developing a plugin, which has a screen where an orientation lock is required. When the plugin's screen has disappeared I want to restore the previous screen status. With the current API, I am not able to tell if the screen was locked or not and I don't want to unlock it if the main application had a good reason to lock it in the first place.

Code snippet required:

screenObject.getCurrentOrientation = function() {
    	return screenOrientation.currOrientation;
    };

**Comment by tony--** [comment]
@TorokDaniel - If I understand correctly, you want to be able to know if the orientation is locked or unlocked.  I think this will be possible after the plugin is updated to the latest spec (see #102).  There are some details I'm not sure about.  For example, if the Orientation preference is set to Portrait and this plugin is installed but the orientation is not currently locked by the plugin, what behavior would you expect?  I guess in this case, the plugin should detect that the orientation is locked to portrait even though this was done via preference instead of via this plugin?

**Comment by tony--** [comment]
Migrated to Apache Cordova JIRA [CB-11360](https://issues.apache.org/jira/browse/CB-11360)
